### ISSUE TITLE
Models without bullet impacts and without penetration.

### ISSUE THREAD

**Issue by ij1shoot** [marv7000/BetterBlenderCOD#3]
Hello, first thanks for maintaining the plugin; well, I really don't know the problem is on my side, my models don't have bullet impacts, and they don't penetrate the model either, I'm on 3.1.2, I haven't had this problem with the alpha version 0.3.5 on 2.63, I tried importing some .psk that worked for me in 0.3.5, but no luck, the model looks fine but has these problems, may be I have to activate some option in blender? Cheers.

**Comment by marv7000** [comment]
When you're talking about bullet impacts, do you mean the behavior in BO3?

**Comment by Scobalula** [comment]
Just to confirm, you have actually applied the collision LOD setting within Asset Manager? 
![image](https://user-images.githubusercontent.com/12156105/165773418-7c419e59-df2d-4a24-870f-0a1f7c7a21db.png)

**Comment by Scobalula** [comment]
I tested a simple torus from Blender and imported it into a map and bullet collision worked. 

![image](https://user-images.githubusercontent.com/12156105/165777760-70dccc70-40a5-4028-8edc-5f78d102a56c.png)

**Comment by ij1shoot** [comment]
mmh I see, well I don't know what the problem is, in 2.63 I simply import the model and export it with 0.3.5

**Comment by marv7000** [comment]
Must be on your side, works fine for me. Check your AssMan settings again,

**Comment by ij1shoot** [comment]
can it be because i am using w7?

**Comment by marv7000** [comment]
Do you mean Windows 7?

**Comment by ij1shoot** [comment]
yes, windows 7, my pc is old

**Comment by marv7000** [comment]
Don't know if that will affect it, but I can only give support for Windows 10 unfortunately. The issue is definitely on your side.

**Comment by ij1shoot** [comment]
hello, i just created a toroid, if I shoot from "inside" the texture, i get hits, i guess i need to do something else, any tip? or is there any tutorial for this plugin in blender 3?
![image](https://user-images.githubusercontent.com/69841825/165982654-db69e5bf-de99-42bc-9b44-51f244da345e.png)
