### ISSUE TITLE
Asking for my friend

### ISSUE THREAD

**Issue by Bordomkillsme** [marv7000/BetterBlenderCOD#4]
Hello my friend was wondering is it possible to export a level? Because when he tried to do that this happened
![image](https://user-images.githubusercontent.com/76572302/165862759-0e479c88-7a21-493f-a5c1-1e952616122d.png)

**Comment by marv7000** [comment]
It should be possible, this is a known issue at the moment. The script errors when you try to export multiple seperate meshes. I haven't gotten around to fixing this so please wait for a few days.

**Comment by Bordomkillsme** [comment]
I see thanks for the respond
